package jira

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"io"
	"net/http"
	"strconv"
	"strings"
	"time"

	"code-agent/pkg/providers"
)

// jiraWebhookEnvelope is the shape Atlassian sends. We only care about
// `webhookEvent` and `issue`.
type jiraWebhookEnvelope struct {
	Timestamp      int64  `json:"timestamp"`
	WebhookEvent   string `json:"webhookEvent"`
	Issue          *issue `json:"issue"`
	IssueEventType string `json:"issue_event_type_name,omitempty"`
}

// HandleWebhook validates the optional shared-secret HMAC and emits an Event.
//
// Atlassian Cloud doesn't sign webhooks itself, so the convention is for the
// orchestrator to require an `X-Hub-Signature-256` header generated by a
// proxy/relay (or Forge), or — fallback — a `?secret=` token comparison.
func (p *Provider) HandleWebhook(w http.ResponseWriter, r *http.Request, out chan<- providers.Event) {
	defer r.Body.Close()
	body, err := io.ReadAll(io.LimitReader(r.Body, 5<<20))
	if err != nil {
		http.Error(w, "read body", http.StatusBadRequest)
		return
	}

	if secret := p.board.Triggers.Webhook.Secret.Value(); secret != "" {
		if !verifySig(r, body, secret) {
			p.logger.Warn().Msg("jira webhook: bad signature")
			http.Error(w, "bad signature", http.StatusUnauthorized)
			return
		}
	}

	var env jiraWebhookEnvelope
	if err := json.Unmarshal(body, &env); err != nil {
		http.Error(w, "bad json", http.StatusBadRequest)
		return
	}
	if env.Issue == nil {
		w.WriteHeader(http.StatusNoContent)
		return
	}

	t := p.toTicket(*env.Issue)
	if !p.matchesFilters(t) {
		w.WriteHeader(http.StatusNoContent)
		return
	}

	evtType := classifyJiraEvent(env.WebhookEvent)
	key := env.Issue.Key + ":" + strconv.FormatInt(env.Timestamp, 10)

	out <- providers.Event{
		BoardID:    p.board.ID,
		Provider:   "jira",
		Source:     "webhook",
		Type:       evtType,
		Ticket:     t,
		Key:        key,
		ReceivedAt: time.Now(),
	}
	w.WriteHeader(http.StatusAccepted)
}

func (p *Provider) matchesFilters(t providers.Ticket) bool {
	if len(p.board.Filters.Labels) > 0 {
		want := map[string]bool{}
		for _, l := range p.board.Filters.Labels {
			want[strings.ToLower(l)] = true
		}
		ok := false
		for _, l := range t.Labels {
			if want[strings.ToLower(l)] {
				ok = true
				break
			}
		}
		if !ok {
			return false
		}
	}
	for _, l := range p.board.Filters.ExcludeLabels {
		ll := strings.ToLower(l)
		for _, lab := range t.Labels {
			if strings.ToLower(lab) == ll {
				return false
			}
		}
	}
	return true
}

func classifyJiraEvent(name string) string {
	switch {
	case strings.HasSuffix(name, "issue_created"):
		return "created"
	case strings.HasSuffix(name, "issue_updated"):
		return "updated"
	case strings.HasSuffix(name, "comment_created"), strings.HasSuffix(name, "comment_updated"):
		return "commented"
	default:
		return "updated"
	}
}

func verifySig(r *http.Request, body []byte, secret string) bool {
	got := r.Header.Get("X-Hub-Signature-256")
	if got == "" {
		// fallback: ?secret= query parameter
		if r.URL.Query().Get("secret") == secret {
			return true
		}
		return false
	}
	got = strings.TrimPrefix(got, "sha256=")
	mac := hmac.New(sha256.New, []byte(secret))
	mac.Write(body)
	want := hex.EncodeToString(mac.Sum(nil))
	return hmac.Equal([]byte(got), []byte(want))
}
